# Default values for spire.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# image:
#   repository: gcr.io/spiffe-io
#   pullPolicy: IfNotPresent
#   tag: "1.0.2"

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

# server:
#   trustDomain: bigbang.dev
#   clusterName: demo-cluster

# agent:
#   # verification should be disabled in some environments, including Minikube
#   kubeletSkipVerification: false


server:
  trustDomain: bigbang.dev

  bundle:
    nodePort: 32767

  federatesWith: []
    # - trustDomain: "other.domain" 
    #   endpoint: https://host.k3d.internal:8443
    #   spiffe: spiffe://other.domain/spire/server

  service:
    type: ClusterIP
    port: 8443

istio: 
  spire:
    # Toggle vs creation
    enabled: true
    annotations: {}
    labels: {}
    gateways:
      - istio-system/passthrough
    hosts:
      - spire.{{ .Values.hostname }}
    service: ""
    port: ""
    namespace: ""
        