apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: http-bundle
      port: 8443
      targetPort: 8443
      protocol: TCP
      nodePort: {{ .Values.server.bundle.nodePort }}
  selector:
    app: spire-server
